jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -B package
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
